### ISSUE TITLE
Getting error.

### ISSUE THREAD

**Issue by jignesh87** [GianlucaGuarini/nodejs-MySQL-push-notifications-demo#3]
Hello,Gianluca
I am using your demo, but getting following error.

"NetworkError: 404 Not Found - http://192.168.1.67/nodejs-MySQL-push-notifications-demo-master/socket.io/socket.io.js"

ReferenceError: io is not defined
var socket = io.connect('http://localhost:8000');

Is there any need to include file except client.html and server.js?

There is no file as named "socket.io.js" in source.

Thanks,
Jignesh.

**Comment by GianlucaGuarini** [comment]
I guess you started the server using `$ node server` right?

**Comment by jignesh87** [comment]
No.

**Comment by jignesh87** [comment]
Please tell me steps for successful execution.

**Comment by GianlucaGuarini** [comment]
check this http://www.gianlucaguarini.com/blog/push-notification-server-streaming-on-a-mysql-database/
