### ISSUE TITLE
How to query and display multiple tables in mysql db

### ISSUE THREAD

**Issue by nuwee-de** [GianlucaGuarini/nodejs-MySQL-push-notifications-demo#5]
Your script has been extremely useful but I would like to know whether it is possible to query multiple tables and push the data to single html page at once by using your script.
Thank you.

**Comment by GianlucaGuarini** [comment]
You can query whatever you want [here](https://github.com/GianlucaGuarini/nodejs-MySQL-push-notifications-demo/blob/master/server.js#L51)

**Comment by nuwee-de** [comment]
Yes, but is it possible to query, say about two or three mysql tables at once AND push the data into three separate arrays at once??
eg:
var query = connection.query('SELECT \* FROM users');
var query2 = connection.query('SELECT \* FROM projects');
var query3 = connection.query('SELECT \* FROM pending');.
And push the data into three separate arrays user[],user2[],user3[]
Thank you.
